[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
axum-core = "0.4.5"
ipnet = "2.10.1"
tokio = { version = "1.42.0", features = ["full"] }

[lints]
workspace = true
