[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
axum-core = "0.4.5"
clap = { version = "4.5.23", features = ["derive"] }
ipnet = "2.10.1"
systemd = "0.10.0"
tokio = { version = "1.42.0", features = ["full"] }

[lints]
workspace = true
